name = "timerx-website"

compatibility_date = "2025-03-13"
compatibility_flags = ["nodejs_compat"]

main = "./.next/standalone/server.js" # Use Next.js standalone mode for Cloudflare
assets = { directory = ".next/static", binding = "ASSETS" }
